import React from 'react';
import PageTemplate from '../components/PageTemplate';

const WritingPromptsPage: React.FC = () => {
  const metadata = {
    title: 'Random Writing Prompt Generator - Free Writing Prompts',
    description: 'Generate unlimited writing prompts instantly with our free writing prompt generator. Create unique story ideas with compelling conflicts, emotional stakes, and creative plot twists to overcome writer\'s block.',
    keywords: 'writing prompts, random writing prompts, writing prompt generator, story prompts, creative writing prompts, random story prompt generator',
    canonical: 'https://randomprompts.org/writing-prompts',
    h1: 'Random Writing Prompt Generator',
    subtitle: 'Generate unlimited writing prompts instantly. Our free writing prompt generator creates unique story ideas with compelling conflicts, emotional stakes, and creative plot twists to spark your creativity and overcome writer\'s block.'
  };

  const faqs = [
    {
      question: 'What are writing prompts?',
      answer: 'Writing prompts are short ideas or situations designed to inspire new stories, essays, or creative pieces. They help overcome writer\'s block and spark creativity.'
    },
    {
      question: 'How do I use writing prompts effectively?',
      answer: 'Choose a prompt that catches your interest, set a timer (10–15 minutes), and start writing without overthinking. Let the prompt lead your imagination.'
    },
    {
      question: 'Can I use these writing prompts for commercial projects?',
      answer: 'Yes. All writing prompts on RandomPrompts.org are free to use for personal or commercial purposes — no attribution required.'
    },
    {
      question: 'Are the writing prompts generated by AI?',
      answer: 'Yes. Our Random Prompts Generator uses AI-assisted templates to produce unique, high-quality writing ideas across genres and tones.'
    },
    {
      question: 'What types of writing prompts can I generate?',
      answer: 'You can create prompts for fiction, poetry, blogging, journaling, or screenwriting — including genres like fantasy, romance, mystery, and sci-fi.'
    }
  ];

  const seoContent = (
    <div className="prose prose-gray max-w-none">
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Random Writing Prompts - Professional Story Ideas</h2>
      <p className="text-gray-700 mb-4">
        Our random writing prompt generator creates professional writing prompts designed to spark creativity and overcome writer's block. This free writing prompt generator delivers unlimited story ideas featuring unique conflicts, emotional stakes, and compelling plot twists. Each randomly generated prompt combines proven story elements with sophisticated narratives perfect for creative writers, novelists, and storytellers.
      </p>
      <p className="text-gray-700 mb-4">
        Generate random writing prompts with detailed character archetypes (memory thieves, dream architects, retired superheroes), specific story conflicts, and creative plot twists that go beyond generic writing prompts. This random story prompt generator tool is ideal for daily writing practice, NaNoWriMo preparation, creative writing exercises, and exploring new narrative ideas.
      </p>
      <div className="bg-blue-50 p-4 rounded-lg mt-4">
        <h3 className="font-semibold text-blue-900 mb-2">Quality Features:</h3>
        <ul className="text-blue-800 text-sm space-y-1">
          <li>• Emotional stakes and internal conflicts</li>
          <li>• Specific, evocative settings beyond generic locations</li>
          <li>• Complex character archetypes with built-in motivations</li>
          <li>• Plot twists that recontextualize the entire story</li>
        </ul>
      </div>
    </div>
  );

  return <PageTemplate category="writing" metadata={metadata} faqs={faqs} seoContent={seoContent} />;
};

export default WritingPromptsPage;
