import React from 'react';
import { Link } from 'react-router-dom';
import Header from './components/Header';
import Footer from './components/Footer';
import SEO from './components/SEO';
import { FileText } from 'lucide-react';

const TermsPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-white">
      <SEO
        path="terms"
        title="Terms of Service - Random Prompts Generator"
        description="Terms of service for Random Prompts Generator. Learn about legal terms, user responsibilities, intellectual property, and usage guidelines for our prompt generator."
        keywords="terms of service, website policy, RandomPrompts terms, legal terms, user agreement"
      />

      <Header />

      {/* Hero Section */}
      <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white py-16">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <div className="flex justify-center mb-4">
            <FileText size={48} />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            Terms of Service
          </h1>
          <p className="text-lg opacity-90">
            Please read these terms carefully before using Random Prompts Generator
          </p>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
          <div className="prose prose-gray max-w-none">
            <p className="text-sm text-gray-500 mb-8">
              <strong>Last Updated:</strong> October 30, 2025
            </p>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Agreement to Terms</h2>
              <p className="text-gray-700 mb-4">
                By accessing or using Random Prompts Generator at{' '}
                <a href="https://randomprompts.org" className="text-blue-600 hover:underline">
                  https://randomprompts.org
                </a>{' '}
                ("the Service"), you agree to be bound by these Terms of Service ("Terms").
                If you do not agree to these Terms, please do not use the Service.
              </p>
              <div className="bg-blue-50 border-l-4 border-blue-500 p-4 mb-4">
                <p className="text-blue-900 text-sm">
                  <strong>Quick Summary:</strong> By using our site, you agree to these terms.
                  Use it responsibly, respect intellectual property, and don't do anything harmful or illegal.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Service Description</h2>
              <p className="text-gray-700 mb-4">
                Random Prompts Generator is a free web-based tool that generates creative prompts for:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>Creative writing and storytelling</li>
                <li>AI art generation (MidJourney, Stable Diffusion, DALL-E, etc.)</li>
                <li>Blog post ideation and content creation</li>
                <li>Fantasy worldbuilding and character development</li>
                <li>Character name generation</li>
              </ul>
              <p className="text-gray-700 mb-4">
                The Service is provided free of charge with no registration required. Learn more about
                AI writing tools at{' '}
                <a
                  href="https://openai.com/research"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:underline"
                >
                  OpenAI Research
                </a>.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Intellectual Property & Usage Rights</h2>

              <h3 className="text-xl font-semibold text-gray-800 mb-3">Your Rights to Generated Content</h3>
              <div className="bg-green-50 border-l-4 border-green-500 p-4 mb-4">
                <p className="text-green-900 font-semibold mb-2">
                  ✓ You OWN the prompts you generate
                </p>
                <ul className="text-green-800 text-sm space-y-1">
                  <li>✓ Use them for personal projects (free)</li>
                  <li>✓ Use them for commercial projects (free)</li>
                  <li>✓ Modify and adapt them however you like</li>
                  <li>✓ No attribution required (but appreciated!)</li>
                </ul>
              </div>
              <p className="text-gray-700 mb-4">
                All prompts generated by Random Prompts Generator are provided to you royalty-free.
                You have full rights to use, modify, distribute, and commercialize any prompts
                generated through our Service without restriction.
              </p>

              <h3 className="text-xl font-semibold text-gray-800 mb-3">Our Intellectual Property</h3>
              <p className="text-gray-700 mb-4">
                The Random Prompts Generator website, including its design, code, algorithms, and
                branding, is open source and available on{' '}
                <a
                  href="https://github.com/rakela/random-prompts-generator"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:underline"
                >
                  GitHub
                </a>.
                You may use, modify, and distribute the code according to the repository's license.
              </p>

              <h3 className="text-xl font-semibold text-gray-800 mb-3">Third-Party Content</h3>
              <p className="text-gray-700 mb-4">
                When using prompts with third-party AI services (e.g., MidJourney, ChatGPT, Stable Diffusion),
                you are subject to those platforms' terms of service. We recommend reviewing:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>
                  <a
                    href="https://openai.com/policies"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                  >
                    OpenAI Terms of Use
                  </a> (ChatGPT, DALL-E)
                </li>
                <li>
                  <a
                    href="https://midjourney.com/terms"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                  >
                    MidJourney Terms of Service
                  </a>
                </li>
                <li>
                  <a
                    href="https://stability.ai/terms"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                  >
                    Stability AI Terms
                  </a> (Stable Diffusion)
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">User Responsibilities</h2>
              <p className="text-gray-700 mb-4">
                When using Random Prompts Generator, you agree to:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>Use the Service in a lawful and ethical manner</li>
                <li>Not attempt to scrape, harvest, or mass-download content</li>
                <li>Not attempt to reverse-engineer or compromise the Service</li>
                <li>Not use the Service to create harmful, illegal, or offensive content</li>
                <li>Respect intellectual property rights when using generated prompts</li>
                <li>Not overload or disrupt the Service's infrastructure</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Content Guidelines</h2>
              <p className="text-gray-700 mb-4">
                While we do not monitor or control how you use generated prompts, we expect users to:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>Follow applicable laws and regulations in their jurisdiction</li>
                <li>Respect the terms of service of third-party AI platforms</li>
                <li>Not use prompts to create content that infringes on others' rights</li>
                <li>Exercise judgment and ethical consideration in creative work</li>
              </ul>
              <p className="text-gray-700 mb-4">
                For guidance on ethical AI use, visit{' '}
                <a
                  href="https://huggingface.co"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:underline"
                >
                  Hugging Face
                </a>, a community-driven AI platform with ethical AI resources.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Disclaimers and Limitations</h2>

              <h3 className="text-xl font-semibold text-gray-800 mb-3">Service Availability</h3>
              <p className="text-gray-700 mb-4">
                Random Prompts Generator is provided "as is" without warranties of any kind. We do not
                guarantee:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>Continuous, uninterrupted access to the Service</li>
                <li>Error-free operation or bug-free experience</li>
                <li>Specific results or outcomes from generated prompts</li>
                <li>Compatibility with all devices or browsers</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-800 mb-3">Content Quality</h3>
              <p className="text-gray-700 mb-4">
                Generated prompts are created algorithmically and may occasionally produce:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>Repetitive or nonsensical results</li>
                <li>Content that requires editing or refinement</li>
                <li>Prompts that don't meet your specific needs</li>
              </ul>
              <p className="text-gray-700 mb-4">
                We recommend reviewing and adapting generated prompts to suit your creative vision.
              </p>

              <h3 className="text-xl font-semibold text-gray-800 mb-3">External Links</h3>
              <p className="text-gray-700 mb-4">
                Our Service contains links to external websites and resources. We are not responsible for:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>The content or privacy practices of external sites</li>
                <li>The accuracy or reliability of third-party information</li>
                <li>Any transactions or interactions with external services</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Limitation of Liability</h2>
              <p className="text-gray-700 mb-4">
                To the fullest extent permitted by law, Random Prompts Generator and its creators,
                contributors, and affiliates shall not be liable for:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>Any indirect, incidental, or consequential damages</li>
                <li>Loss of data, profits, or creative work</li>
                <li>Issues arising from the use of generated prompts</li>
                <li>Disputes with third-party AI platforms or services</li>
                <li>Technical malfunctions or service interruptions</li>
              </ul>
              <p className="text-gray-700 mb-4">
                Your use of the Service is at your own risk.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Privacy and Data</h2>
              <p className="text-gray-700 mb-4">
                Your privacy is important to us. Please review our{' '}
                <Link to="/privacy" className="text-blue-600 hover:underline">
                  Privacy Policy
                </Link>{' '}
                to understand how we handle data. Key points:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>We do NOT collect personal information</li>
                <li>No registration or account creation required</li>
                <li>Generated prompts are NOT stored on our servers</li>
                <li>Only anonymous usage analytics via Google Analytics</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Changes to Service and Terms</h2>
              <p className="text-gray-700 mb-4">
                We reserve the right to:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>Modify or discontinue the Service at any time</li>
                <li>Update these Terms of Service with notice on this page</li>
                <li>Add or remove features without prior notice</li>
                <li>Change pricing (though the Service is currently free)</li>
              </ul>
              <p className="text-gray-700 mb-4">
                Continued use of the Service after changes constitutes acceptance of updated Terms.
                Check back periodically for updates.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Open Source and Community</h2>
              <p className="text-gray-700 mb-4">
                Random Prompts Generator is an open-source project. You can:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>
                  View the source code on{' '}
                  <a
                    href="https://github.com/rakela/random-prompts-generator"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                  >
                    GitHub
                  </a>
                </li>
                <li>
                  Report issues or suggest features on{' '}
                  <a
                    href="https://github.com/rakela/random-prompts-generator/issues"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                  >
                    GitHub Issues
                  </a>
                </li>
                <li>
                  Contribute improvements via pull requests
                </li>
                <li>
                  Fork and adapt the project for your own use
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Governing Law</h2>
              <p className="text-gray-700 mb-4">
                These Terms shall be governed by and construed in accordance with applicable laws.
                Any disputes arising from the use of the Service shall be resolved through good-faith
                negotiation or appropriate legal channels.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Severability</h2>
              <p className="text-gray-700 mb-4">
                If any provision of these Terms is found to be unenforceable or invalid, the remaining
                provisions shall continue in full force and effect.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact and Support</h2>
              <p className="text-gray-700 mb-4">
                For questions, issues, or feedback regarding these Terms or the Service:
              </p>
              <ul className="list-none pl-0 text-gray-700 mb-4 space-y-2">
                <li>
                  <strong>GitHub Issues:</strong>{' '}
                  <a
                    href="https://github.com/rakela/random-prompts-generator/issues"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                  >
                    Report an issue
                  </a>
                </li>
                <li>
                  <strong>GitHub Discussions:</strong>{' '}
                  <a
                    href="https://github.com/rakela/random-prompts-generator/discussions"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                  >
                    Community discussions
                  </a>
                </li>
                <li>
                  <strong>Documentation:</strong>{' '}
                  <a
                    href="https://www.termsfeed.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                  >
                    TermsFeed
                  </a> - Terms of service resources
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Summary</h2>
              <div className="bg-blue-50 border-l-4 border-blue-500 p-6">
                <p className="text-blue-900 font-semibold mb-2">In Plain English:</p>
                <ul className="text-blue-800 text-sm space-y-2">
                  <li>✓ Use the Service responsibly and ethically</li>
                  <li>✓ You own the prompts you generate — use them freely</li>
                  <li>✓ We provide the Service "as is" with no guarantees</li>
                  <li>✓ Open source, free, and community-driven</li>
                  <li>✓ Respect intellectual property and third-party terms</li>
                  <li>✓ Contact us on GitHub if you have questions</li>
                </ul>
              </div>
            </section>
          </div>

          <div className="mt-8 pt-8 border-t border-gray-200">
            <p className="text-sm text-gray-500 text-center">
              Want to learn more about our privacy practices?{' '}
              <Link to="/privacy" className="text-blue-600 hover:underline">
                Read our Privacy Policy
              </Link>
              {' '}or{' '}
              <Link to="/" className="text-blue-600 hover:underline">
                start generating prompts
              </Link>.
            </p>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default TermsPage;
